name: Lint/Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
jobs:
  lint_test:
    runs-on: ubuntu-latest
    container: python@sha256:03dbfdaf2cad49d26ff45dda0fb12db9d087282303e0675315ff14cda0bb6955  # 3.10-slim-bullseye
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fix $PATH
        run: echo "$HOME/.poetry/bin" >> "$GITHUB_PATH"
      - name: Install dependencies
        run: |
          apt update -y
          apt install -y make curl
          curl https://raw.githubusercontent.com/python-poetry/poetry/68649946fe09d52ed1a5844bda6690ba6327c408/get-poetry.py --output get-poetry.py
          python get-poetry.py --version=1.1.13 --yes
          make requirements
      - name: Lint
        run: make lint
      - name: Execute script
        run: |
          make run
          make show-hashes
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: out
